import { BaseDocument, FirestoreTimestamp } from "./firestore";

// ─── Sub-types ────────────────────────────────────────────────────────────────

/** AI risk tier classification. */
export type RiskTier = "low" | "medium" | "high";

/**
 * A single factor contributing to a worker's risk / premium calculation.
 * Surfaced to the worker as a plain-language explanation.
 */
export interface RiskFactor {
  /** Factor identifier, e.g. "zone_flood_history", "shift_heat_exposure". */
  factor: string;

  /** Relative weight / contribution to the premium (0 – 1). */
  weight: number;

  /** Plain-language description shown to the worker. */
  description: string;
}

// ─── RiskScore Document ──────────────────────────────────────────────────────

/**
 * Firestore collection: `riskScores`
 *
 * Weekly AI-computed risk profile for a worker in a specific zone.
 * Generated by the Premium Engine (XGBoost) and Disruption Forecasting
 * Engine (Prophet). Feeds into premium personalisation and rider alerts.
 */
export interface RiskScore extends BaseDocument {
  /** Worker this risk score applies to. */
  workerId: string;

  /** Zone ID this score was computed for. */
  zoneId: string;

  /** Start of the week this forecast covers. */
  weekOf: FirestoreTimestamp;

  /** Overall risk classification. */
  riskTier: RiskTier;

  /**
   * Predicted probability of a triggerable disruption this week (0 – 1).
   * Output of the Prophet forecasting model.
   */
  disruptionProbability: number;

  /** AI-suggested premium in ₹, or `null` if not computed. */
  premiumSuggestion: number | null;

  /**
   * Top contributing factors driving the risk / premium.
   * Typically the top 2 – 3 factors from XGBoost feature importance.
   */
  factors: RiskFactor[];

  /** Version identifier of the ML model that produced this score. */
  modelVersion: string;
}
